### ISSUE TITLE
TODO Near future

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [kleinesfilmroellchen/sof-language#2]
- [ ] Correct `def` scoping behavior (Nametable search priority tree, Namtable definition priority tree)
- [ ] Instant computation with primitive callables. E.g. `n . 3 + n def` -> `n 3 +`
- [ ] Implement code blocks
- [ ] Turing completeness (needs code blocks): Implement `if` and `while` PTs
- [ ] How to do the `else` and `elseif` PTs? Invisible stack element?
- [ ] Functions
- [ ] Lists (pretty simple but low priority)
- [ ] Namespaces; check `def`'s nametable traversal algorithm
- [ ] `use` PT for multi-file projects
- [ ] Standard library: Math, Data structures, Functional tools (curry, list stuff, generators?), FileIO, Networking?
- [ ] Objects: Function attachment algorithm for class nametable discovery, class and object nametable layout, `attribute` PT in constructors

These are the main parts of v 0.1, without them, I will not consider SOF a universal programming language.

**Comment by kleinesfilmroellchen** [comment]
7578bbc implements instant/direct computation

**Comment by kleinesfilmroellchen** [comment]
b1184edadb17e07df8b2f6e8c95ca28edb4d871f implements currying
